name: Update LinkedIn JSON

# Déclenchement automatique tous les jours à 6h UTC, ou à la main
on:
  schedule:
    - cron: '0 6 * * *'  # tous les jours à 6h UTC
  workflow_dispatch:      # bouton manuel dans GitHub Actions

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer feedparser
        run: pip install feedparser

      - name: Exécuter le script Python
        run: python scripts/fetch_linkedin_rss.py

      - name: Commit & push si modification
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/linkedin-posts.json
          git commit -m "Mise à jour auto des posts LinkedIn" || echo "Aucun changement"
          git push
